name: FibonacciSequence

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build-push-images:
    name: Building and publishing images on repository
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: QuemActions set-up
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wojtekpodmokly/fibonaccisequence
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          buildkit: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=docker.io/wojtekpodmokly/fibonaccisequence:cache
          cache-to: type=registry,ref=docker.io/wojtekpodmokly/fibonaccisequence:cache,mode=max
